### ISSUE TITLE
Image scaling and rotation issues.

### ISSUE THREAD

**Issue by scottrhoyt** [mindbrix/UIImage-PDF#37] opened 2015-03-03 01:30 UTC
Thank you for the great category!  I am using it to display pdf document pages as images in my app.

Firstly, I encountered an issue where some images are being rendered with a different than intended rotation.  I believe I tracked this down to the /Rotate tag in the pdf not being honored while rendering.  I came across the function, `CGPDFPageGetDrawingTransform`, that I used to replace the scaling and translating transforms in PDFView.m.  This seems to have solved the problem.

Secondly, the resulting images that are being rendered are of low quality when displayed.  They are of the intended size (taking into account screen scale), but perhaps the screen scale is not being taken into account somewhere?  I noticed there was no reference to scale in the PDFView.m functions (including implied in  the `size` parameter)... though you are passing in a context that has been scaled by the screen scale factor.  Is this enough to ensure the PDFs are rendered at the proper size?  Any other thoughts on what may be the issue?

**Comment by skela** [comment] 2015-05-19 01:55
I too am having issues with the orientation of the image made from a PDF using this library.
@scottrhoyt , where did you put the modifications to correct this ?

**Comment by mindbrix** [comment] 2015-05-19 08:09
@scottrhoyt thanks for raising this. Can you submit your fix as a pull request? I'd like to see your code ;-)

**Comment by scottrhoyt** [comment] 2015-05-19 18:35
I submitted a pull request with the code changes I made for orientation/scale. Didn't test extensively, but it solved the issues for me.

**Comment by mindbrix** [comment] 2015-05-19 20:43
Thanks. I shall test it. Can you send me some examples PDFs where the rotation and scaling is wrong?

**Comment by scottrhoyt** [comment] 2015-05-19 21:18
I'm done with the project that I was working on when I came across this, so I don't have access to the original files. However, I believe I identified the problem as stemming from when PDFs are rotated using the `\Rotate` tag in the PDF instead of being saved with new dimensions/orientation. This is most often seen not with a PDF vector image workflow, but instead with PDF documents where one or more pages in the document was rotated using this tag. We came across this when performing rotations in Acrobat. The transform function I used takes into account the `\Rotate` tag. I created a sample image that I believe should replicate this behavior here:

https://dl.dropboxusercontent.com/u/18408411/QuestionMark.pdf

I needed to remember to clean the project in between tests because of the default caching to disk.

**Comment by mindbrix** [comment] 2015-05-20 10:46
Issue fixed by #38

**Comment by skela** [comment] 2015-05-20 10:59
I tested it and it does indeed sort things out for the rotation, but I think the width and the height are the wrong way around. At least when I try it with my PDFs it seems to be the case. Same goes for the question mark. Its wider than the PDF suggests, and the only thing I can think of is that its got the dimensions the wrong way around.

**Comment by mindbrix** [comment] 2015-05-20 11:13
Hi. I think that the last parameter of `CGPDFPageGetDrawingTransform()` in `renderIntoContext:` should be set to `YES`.

Can you see if that works?

**Comment by mindbrix** [comment] 2015-05-20 11:14
@skela thanks for this.

**Comment by mindbrix** [comment] 2015-05-20 11:16
![ios simulator screen shot 20 may 2015 12 15 57](https://cloud.githubusercontent.com/assets/177889/7724502/fd8f7a7e-fee9-11e4-81e5-badd35584cf0.png)

**Comment by skela** [comment] 2015-05-20 11:19
@mindbrix np, i love yer work, happy to try and help ;)

Anyway, I tried setting the last parameter to YES for renderInContext as you suggested, and yes that did fix that issue, but introduced another one.

Basically now the Image has large areas of unused space, meaning its probably still got the dimensions the wrong way around. My gut feeling is there is probably a better fix than that.

**Comment by mindbrix** [comment] 2015-05-20 11:21
@skela what PDF are you using to test?

**Comment by skela** [comment] 2015-05-20 11:22
@mindbrix can I send it to you privately? Its a file provided by a client, don't want everybody to have it.

**Comment by mindbrix** [comment] 2015-05-20 11:22
nigel@mindbrix.co.uk

**Comment by skela** [comment] 2015-05-20 11:23
@mindbrix thanks mate, will send it to you now.

**Comment by skela** [comment] 2015-05-20 11:27
@mindbrix ok, should be in your inbox any second now.

**Comment by mindbrix** [comment] 2015-05-21 13:37
@skela I have created a branch at https://github.com/mindbrix/UIImage-PDF/tree/fixTransforms

This should fix your issues. Can you please test and let me know.

**Comment by skela** [comment] 2015-05-21 14:45
@mindbrix I've tried the changes in that branch, its still got quite a bit of an empty space caused by the dimensions being the wrong way around. I'll send you the comparative results in an email so you can see what I mean.

**Comment by mindbrix** [comment] 2015-05-21 14:50
@skela interesting, as I now have code to handle that.

**Comment by skela** [comment] 2015-05-21 15:01
@mindbrix , for the record I'm using your [UIImage originalSizeImageWithPDFURL:(NSURL*)URL] ? category method.

just sent the email, should be with you any second ;)

**Comment by mindbrix** [comment] 2015-05-21 19:57
@skela I've merged the changes. Thanks for your invaluable help ;-)

**Closed by mindbrix** 2015-05-21 19:57 UTC

**Comment by skela** [comment] 2015-05-22 01:59
@mindbrix awesome, cheers!
